### ISSUE TITLE
User Creation - Phone Validation

### ISSUE THREAD

**Issue by DanielOaks** [markbil/RFIDCheckinSystem#6]
Heya guys. I noticed something strange about the user creation page.

There are three boxes for parts of the phone number, and it says the first and second boxes need to have three digits, and the last box needs to have four. I think it would do better if it were changed to two digits in the first box, and four in the last two boxes, to cater more towards Australia's phone system.

For instance, 07 means QLD, 04 means mobile phones, so it makes more sense to me to have the first digit accept the area code. If we wanted to, we could even just combine it into a single box, to make it easier for people.

**Comment by markbil** [comment]
I suggest to turn the three fields into one field for the entire phone number. @geek-boy do we need to make changes in the backend for that?

**Comment by geek-boy** [comment]
Hey Mark & Daniel - the phone number was a hangover from the ion_auth code that i added in. we don't need to collect the phone number - just remove it!
